### ISSUE TITLE
item not updating

### ISSUE THREAD

**Issue by tirzah2** [elizeuangelo/fvtt-module-item-linking#2]
Hi! maybe i didnt understand how it works, but if i update an item in the compendium and a player has it, shouldnt it update itself automatically? Is there maybe a macro i need to press?

**Comment by elizeuangelo** [comment]
Yes it should, if the item is linked. Some fields won't update automatically, like "quantity" for instance.

Could you provide me some screenshots? What version of Foundry are you running?

**Comment by tirzah2** [comment]
It updates only if i click on Linked, and then reclick. 
![image](https://github.com/elizeuangelo/fvtt-module-item-linking/assets/83312683/98921859-2e21-401b-a726-2695deb0488e)
im running V11 (i skipped the last two mini updates)

**Comment by elizeuangelo** [comment]
Its a bug im gonna fix it soon, ty!

**Comment by tirzah2** [comment]
they call me the bug crusher.

**Comment by elizeuangelo** [comment]
Please try out v1.0.9

**Comment by tirzah2** [comment]
hi.
now its updating but is not calculating the amount of items in the world anymore (the number on the side in the compendium)

**Comment by tirzah2** [comment]
i even tried deleting the linked item and dragging a new item from the compendium to the character sheet, but no number is appearing.
the old numbers are still there. 
Also, i opened a linked item in a character sheet and changed the quantity. It was a normal shield (that had a template in the compendium). The moment i changed the quantity from 1 to 2, it transformed the item from Shield to Armor of the Gnoll Lord.

![image](https://github.com/elizeuangelo/fvtt-module-item-linking/assets/83312683/6cc4d643-e5f7-4d19-9e61-5efc01612c82)

**Comment by tirzah2** [comment]
i had a waterskin linked, i changed the quantity to two and it became a:
![image](https://github.com/elizeuangelo/fvtt-module-item-linking/assets/83312683/376a2174-d299-48ce-9d46-54000d0cad18)

**Comment by tirzah2** [comment]
i reverted to 1.08 and this issue is gone. it shows the numbers again. (but obviously it doesnt update linked items)

**Comment by elizeuangelo** [comment]
The item listing number is a visual bug, should be resolved in v1.0.10

**Comment by elizeuangelo** [comment]
Please try out v1.0.10

**Comment by tirzah2** [comment]
perfect!
