### ISSUE TITLE
Request: Automatically link Compendium items that are granted via Class/Background advancements

### ISSUE THREAD

**Issue by blamowizard** [elizeuangelo/fvtt-module-item-linking#4]
This functionality would be extra nice :) As it stands, no compendium items granted to a PC by the 5e system's level-up automation become linked by this module without manual intervention. I can bypass this by disabling level-up automation in the system settings, then exclusively drag-and-dropping the same items from their compendia, but it'd be lovely to avoid that.

**Comment by elizeuangelo** [comment]
I think this is done, one year later!
